// type-extras.js — 各タイプの動物・偉人データ
// showResult() で TYPE_EXTRAS[t.n] として参照
const TYPE_EXTRAS = {
  1:  { animal:'🦉', animalName:'フクロウ',  famous:[{name:'アルベルト・アインシュタイン',role:'物理学者'},{name:'村上春樹',role:'小説家'},{name:'カール・ユング',role:'心理学者'}] },
  2:  { animal:'🦅', animalName:'ワシ',      famous:[{name:'スティーブ・ジョブズ',role:'Apple共同創業者'},{name:'イーロン・マスク',role:'起業家'},{name:'本田宗一郎',role:'Honda創業者'}] },
  3:  { animal:'🐢', animalName:'カメ',      famous:[{name:'ウォーレン・バフェット',role:'投資家'},{name:'伊能忠敬',role:'測量家'},{name:'渋沢栄一',role:'実業家'}] },
  4:  { animal:'🐺', animalName:'オオカミ',  famous:[{name:'ナポレオン・ボナパルト',role:'戦略家・皇帝'},{name:'武田信玄',role:'戦国武将'},{name:'マーガレット・サッチャー',role:'英国首相'}] },
  5:  { animal:'🦎', animalName:'トカゲ',    famous:[{name:'フランツ・カフカ',role:'作家'},{name:'夏目漱石',role:'小説家'},{name:'エドガー・アラン・ポー',role:'詩人・小説家'}] },
  6:  { animal:'🕷️', animalName:'クモ',      famous:[{name:'レオナルド・ダ・ヴィンチ',role:'芸術家・発明家'},{name:'ニッコロ・マキャヴェッリ',role:'思想家'},{name:'ジークムント・フロイト',role:'精神医学者'}] },
  7:  { animal:'🐍', animalName:'ヘビ',      famous:[{name:'エリザベス1世',role:'英国女王'},{name:'アンゲラ・メルケル',role:'ドイツ首相'},{name:'徳川家光',role:'江戸幕府3代将軍'}] },
  8:  { animal:'🐙', animalName:'タコ',      famous:[{name:'徳川家康',role:'江戸幕府初代将軍'},{name:'カール・マルクス',role:'哲学者・経済学者'},{name:'オットー・フォン・ビスマルク',role:'ドイツ宰相'}] },
  9:  { animal:'🦋', animalName:'チョウ',    famous:[{name:'宮沢賢治',role:'詩人・童話作家'},{name:'ゲーテ',role:'詩人・小説家'},{name:'ウィリアム・ブレイク',role:'詩人・芸術家'}] },
  10: { animal:'🐬', animalName:'イルカ',    famous:[{name:'ヴィンセント・ファン・ゴッホ',role:'画家'},{name:'フリーダ・カーロ',role:'画家'},{name:'尾崎豊',role:'シンガーソングライター'}] },
  11: { animal:'🦌', animalName:'シカ',      famous:[{name:'マザー・テレサ',role:'カトリック修道女'},{name:'フローレンス・ナイチンゲール',role:'看護師・社会改革者'},{name:'緒方貞子',role:'国連難民高等弁務官'}] },
  12: { animal:'🦫', animalName:'ビーバー',  famous:[{name:'アントニオ・ガウディ',role:'建築家'},{name:'坂本龍馬',role:'幕末の志士'},{name:'スティーブン・スピルバーグ',role:'映画監督'}] },
  13: { animal:'🐟', animalName:'サカナ',    famous:[{name:'太宰治',role:'小説家'},{name:'ジャック・ケルアック',role:'作家'},{name:'アルチュール・ランボー',role:'詩人'}] },
  14: { animal:'🦑', animalName:'イカ',      famous:[{name:'フリードリヒ・ニーチェ',role:'哲学者'},{name:'フョードル・ドストエフスキー',role:'小説家'},{name:'ジャン＝ポール・サルトル',role:'哲学者・作家'}] },
  15: { animal:'🐈‍⬛', animalName:'クロネコ', famous:[{name:'シャルル・ボードレール',role:'詩人'},{name:'中原中也',role:'詩人'},{name:'ライナー・マリア・リルケ',role:'詩人'}] },
  16: { animal:'🦚', animalName:'クジャク',  famous:[{name:'ルートヴィヒ・ヴァン・ベートーヴェン',role:'作曲家'},{name:'三島由紀夫',role:'小説家'},{name:'マリア・カラス',role:'オペラ歌手'}] },
  17: { animal:'🦔', animalName:'ハリネズミ',famous:[{name:'ソクラテス',role:'哲学者'},{name:'ベンジャミン・フランクリン',role:'政治家・発明家'},{name:'福沢諭吉',role:'思想家・教育者'}] },
  18: { animal:'🐆', animalName:'チーター',  famous:[{name:'アーネスト・ヘミングウェイ',role:'作家'},{name:'野口英世',role:'細菌学者'},{name:'ロアール・アムンゼン',role:'探検家'}] },
  19: { animal:'🕊️', animalName:'ハト',      famous:[{name:'ネルソン・マンデラ',role:'南アフリカ元大統領'},{name:'バラク・オバマ',role:'米国元大統領'},{name:'マーティン・ルーサー・キング',role:'公民権運動指導者'}] },
  20: { animal:'🦁', animalName:'ライオン',  famous:[{name:'アレクサンダー大王',role:'古代マケドニア王'},{name:'ウィンストン・チャーチル',role:'英国首相'},{name:'豊臣秀吉',role:'戦国武将'}] },
  21: { animal:'🦊', animalName:'キツネ',    famous:[{name:'シャルル＝モーリス・ド・タレーラン',role:'フランス外交官'},{name:'オスカー・ワイルド',role:'劇作家・詩人'},{name:'勝海舟',role:'幕末の政治家'}] },
  22: { animal:'🦈', animalName:'サメ',      famous:[{name:'孫武（孫子）',role:'兵法家'},{name:'真田幸村',role:'戦国武将'},{name:'アンドリュー・カーネギー',role:'実業家'}] },
  23: { animal:'🦒', animalName:'キリン',    famous:[{name:'ヘンリー・キッシンジャー',role:'外交官・政治家'},{name:'陸奥宗光',role:'外務大臣'},{name:'シャルル・ド・ゴール',role:'フランス大統領'}] },
  24: { animal:'🐅', animalName:'トラ',      famous:[{name:'チンギス・カン',role:'モンゴル帝国創始者'},{name:'ジュリアス・シーザー',role:'ローマ将軍・独裁官'},{name:'ルイ14世',role:'フランス国王'}] },
  25: { animal:'🐘', animalName:'ゾウ',      famous:[{name:'オプラ・ウィンフリー',role:'テレビ司会者・実業家'},{name:'モハメド・アリ',role:'プロボクサー'},{name:'エラ・フィッツジェラルド',role:'ジャズ歌手'}] },
  26: { animal:'🐎', animalName:'ウマ',      famous:[{name:'チェ・ゲバラ',role:'革命家'},{name:'マルティン・ルター',role:'宗教改革者'},{name:'マルコムX',role:'公民権運動指導者'}] },
  27: { animal:'🐻', animalName:'クマ',      famous:[{name:'ダイアナ妃',role:'英国王妃'},{name:'アンネ・フランク',role:'日記作家'},{name:'オードリー・ヘプバーン',role:'女優・慈善活動家'}] },
  28: { animal:'🦬', animalName:'バイソン',  famous:[{name:'西郷隆盛',role:'幕末の志士・明治の英雄'},{name:'ジョン・F・ケネディ',role:'米国大統領'},{name:'セオドア・ルーズベルト',role:'米国大統領'}] },
  29: { animal:'🐒', animalName:'サル',      famous:[{name:'チャーリー・チャップリン',role:'映画俳優・監督'},{name:'ウィリアム・シェイクスピア',role:'劇作家・詩人'},{name:'ジム・キャリー',role:'俳優'}] },
  30: { animal:'🐉', animalName:'ドラゴン',  famous:[{name:'エルビス・プレスリー',role:'ミュージシャン'},{name:'デヴィッド・ボウイ',role:'ミュージシャン'},{name:'田中角栄',role:'元内閣総理大臣'}] },
  31: { animal:'🦜', animalName:'インコ',    famous:[{name:'フレディ・マーキュリー',role:'ミュージシャン'},{name:'マイケル・ジャクソン',role:'ミュージシャン'},{name:'美空ひばり',role:'歌手'}] },
  32: { animal:'🐝', animalName:'ハチ',      famous:[{name:'マリリン・モンロー',role:'女優'},{name:'レディー・ガガ',role:'ミュージシャン'},{name:'松任谷由実',role:'シンガーソングライター'}] }
};
